#!/usr/bin/env bash

export REFLOW=$( dirname "${BASH_SOURCE[0]}" )

if [ $1 = "-c" ]; then
    make -s -f ${REFLOW}/digital/Makefile clean
    make -s -f ${REFLOW}/digital/Makefile "${@:2}"
else
    make -s -f ${REFLOW}/digital/Makefile "$@"
fi
